
.SUFFIXES:
.SUFFIXES: .o .F .f .c .C .cc .cxx .F90

.F90.o:
	$(FC) $(FCFLAGS) -c $< -o $@
.F.o:
	$(F77) $(FFLAGS) -c $< -o $@
.f.o:
	$(F77) $(FFLAGS) -c $< -o $@
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
.cxx.o:
	$(CXX) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

SHELL         = /bin/sh


CLM_LIB				= libclm.a
CLM_LIBS                        = -lclm
CLM_DIR                         = clm
CLM_LIB_DEPEND                  = $(PARFLOW_LIB_DIR)/libclm.a

CLM_UTILS_DIR = utils
CLM_CLM1D_DIR = clm1d
CLM_DRV_DIR = drv

LIB_SUFFIX=.a

M4	      =	
RM            = rm -fr
CP            = cp
XARGS	      = 

FC            = /usr/local/bin/mpif90
FCFLAGS       = -Wall -Wunused -fimplicit-none -free -O2

AR	      = ar

######################################################################
# Rules used in all directories.
######################################################################

CLM_CLEAN=$(RM) *.o *.ii *.int.c *.log *.log.* stamp-* core core.* stats -r ti_files ii_files *.mod *.a


